import { useEffect, useMemo, useState } from "react";
import { ArrowLeft, Check, Clock3, Lightbulb, RotateCcw, Timer, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { useAppStore, getSetAnalytics } from "@/lib/studyforge/store";
import { correctLabel } from "@/lib/studyforge/data";
import type { Question, StudyMode } from "@/lib/studyforge/types";
import { cn, formatElapsed } from "@/lib/utils";

export function SessionConfigView() {
  const sets = useAppStore((s) => s.studySets); const activeId = useAppStore((s) => s.activeSetId);
  const config = useAppStore((s) => s.sessionConfig); const setConfig = useAppStore((s) => s.setSessionConfig);
  const navigate = useAppStore((s) => s.navigate); const start = useAppStore((s) => s.startSession);
  const set = sets.find((x) => x.id === activeId) ?? sets[0]; if (!set) return null;
  const modes: { id: StudyMode; title: string; description: string }[] = [
    { id: "mcq", title: "Multiple Choice", description: "Choose the strongest source-grounded answer." },
    { id: "type", title: "Type Answer", description: "Recall the answer without choices." },
    { id: "tf", title: "True / False", description: "Make a quick factual judgment." },
    { id: "flashcards", title: "Flashcards", description: "Reveal, rate confidence, and build retention." },
  ];
  return <div className="max-w-[820px] mx-auto space-y-8">
    <header className="text-center space-y-2 stagger-in"><span className="text-xs font-semibold px-3 py-1 bg-accent-soft text-accent rounded-full inline-block">Study Session</span><h1 className="text-[clamp(1.6rem,3vw,2.1rem)] text-fg">{set.title}</h1><p className="text-muted">Build a focused session around what you need to learn.</p></header>
    <div className="sf-card p-6 sm:p-8 space-y-8">
      <fieldset><legend className="block text-sm font-semibold text-fg mb-3">Study Mode</legend><div className="grid grid-cols-1 sm:grid-cols-2 gap-3">{modes.map((m) => <ModeCard key={m.id} {...m} active={config.mode === m.id} onClick={() => setConfig({ mode: m.id })} />)}</div></fieldset>
      <fieldset><legend className="block text-sm font-semibold text-fg mb-3">Question Count</legend><div className="flex flex-wrap gap-2">{([["all", `All (${set.totalQuestions})`], [10,"10"],[20,"20"],[30,"30"],[50,"50"],[100,"100"]] as const).map(([val,label]) => <button key={String(val)} type="button" onClick={() => setConfig({ count: val })} className={cn("px-4 py-2.5 rounded-md font-medium text-sm min-h-11 transition-colors", config.count === val ? "bg-accent text-accent-fg" : "bg-surface-2 text-fg hover:bg-bg-warm")}>{label}</button>)}</div></fieldset>
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
        <label className="flex items-center justify-between gap-4 rounded-lg border border-border p-4"><span><span className="block font-semibold text-fg text-sm">Speedrun</span><span className="text-xs text-muted">Add a session countdown.</span></span><input type="checkbox" checked={config.speedrun} onChange={(e) => setConfig({ speedrun: e.target.checked })} className="size-5 accent-[var(--sf-accent)]" /></label>
        <label className="flex items-center justify-between gap-4 rounded-lg border border-border p-4"><span><span className="block font-semibold text-fg text-sm">Review due only</span><span className="text-xs text-muted">Focus on scheduled review cards.</span></span><input type="checkbox" checked={config.reviewDueOnly} onChange={(e) => setConfig({ reviewDueOnly: e.target.checked })} className="size-5 accent-[var(--sf-accent)]" /></label>
      </div>
      {config.speedrun && <div className="rounded-lg bg-accent-soft p-4"><label className="block text-sm font-semibold text-fg mb-2">Timer</label><div className="flex flex-wrap gap-2">{[60,180,300,600].map((seconds) => <button key={seconds} type="button" onClick={() => setConfig({ timerSeconds: seconds })} className={cn("px-3 py-2 rounded-md text-sm", config.timerSeconds === seconds ? "bg-accent text-accent-fg" : "bg-surface text-fg")}>{seconds < 60 ? `${seconds}s` : `${seconds / 60} min`}</button>)}</div></div>}
    </div>
    <div className="flex justify-between items-center gap-3"><Button variant="secondary" onClick={() => navigate("detail", set.id)}>Cancel</Button><Button className="px-8" onClick={start}>Start Learning</Button></div>
  </div>;
}

function ModeCard({ title, description, active, onClick }: { title: string; description: string; active: boolean; onClick: () => void }) {
  return <button type="button" onClick={onClick} className={cn("p-4 rounded-lg text-left transition-[border-color,background-color,transform] duration-150 min-h-[6rem]", active ? "border-2 border-accent bg-accent-soft" : "border border-border hover:border-border-strong")}><p className="font-sans font-semibold text-fg mb-1">{title}</p><p className="text-xs text-muted leading-relaxed">{description}</p></button>;
}

export function StudyView() {
  const session = useAppStore((s) => s.session); const exit = useAppStore((s) => s.exitSession); const select = useAppStore((s) => s.selectChoice); const next = useAppStore((s) => s.nextQuestion);
  const typed = useAppStore((s) => s.typedAnswer); const setTyped = useAppStore((s) => s.setTypedAnswer); const submit = useAppStore((s) => s.submitTyped); const flip = useAppStore((s) => s.flipCard); const grade = useAppStore((s) => s.gradeFlashcard); const hint = useAppStore((s) => s.revealHint);
  const q = session?.questions[session.index]; const mode = session?.mode ?? "mcq"; const effectiveType = mode === "flashcards" ? "flashcard" : mode;
  const [remaining, setRemaining] = useState(session?.timeLimitSeconds ?? 0);
  useEffect(() => { if (!session?.timeLimitSeconds) return; setRemaining(Math.max(0, session.timeLimitSeconds - Math.floor((Date.now() - session.startedAt) / 1000))); const id = window.setInterval(() => setRemaining(Math.max(0, session.timeLimitSeconds! - Math.floor((Date.now() - session.startedAt) / 1000))), 1000); return () => clearInterval(id); }, [session?.startedAt, session?.timeLimitSeconds]);
  useEffect(() => { if (session?.timeLimitSeconds && remaining <= 0) next(); }, [remaining, session?.timeLimitSeconds, next]);
  useEffect(() => { if (!session || !q) return; const onKey = (e: KeyboardEvent) => { const target = e.target as HTMLElement | null; if (target && (target.tagName === "INPUT" || target.tagName === "TEXTAREA")) { if (e.key === "Enter" && effectiveType === "type") { e.preventDefault(); session.revealed ? next() : submit(); } return; } if (e.key === "Escape") exit(); if (effectiveType === "flashcard") { if ((e.key === " " || e.key === "Enter") && !session.flipped) { e.preventDefault(); flip(); } if (session.flipped && e.key === "1") grade(false); if (session.flipped && e.key === "2") grade(true); } else if (!session.revealed && (effectiveType === "mcq" || effectiveType === "tf")) { const n = Number(e.key); if (n >= 1 && n <= q.choices.length) select(q.choices[n - 1]); if (effectiveType === "tf" && e.key.toLowerCase() === "t") select("True"); if (effectiveType === "tf" && e.key.toLowerCase() === "f") select("False"); } else if (session.revealed && (e.key === "Enter" || e.key === " ")) { e.preventDefault(); next(); } }; window.addEventListener("keydown", onKey); return () => window.removeEventListener("keydown", onKey); }, [session, q, effectiveType, next, submit, select, flip, grade, exit]);
  if (!session || !q) return <div className="text-center py-16"><p className="text-muted mb-4">No active session.</p><Button variant="secondary" onClick={exit}>Exit</Button></div>;
  const total = session.questions.length, current = session.index + 1, progress = current / total * 100, last = session.answers.find((a) => a.questionId === q.id), isLast = session.index >= total - 1;
  return <div className="max-w-[840px] mx-auto space-y-6 sm:space-y-8">
    <div className="flex items-center justify-between gap-3"><button type="button" onClick={exit} className="text-sm font-medium text-muted hover:text-fg min-h-11">Exit Session</button><span className="text-sm font-bold text-accent tabular-nums">{current} / {total}</span><div className="flex items-center gap-2">{session.timeLimitSeconds && <span className={cn("text-sm font-semibold tabular-nums", remaining <= 30 ? "text-danger" : "text-muted")}><Timer className="size-4 inline mr-1" />{formatClock(remaining)}</span>}<div className="w-16 sm:w-28 h-1.5 bg-surface-2 rounded-full overflow-hidden"><div className="bg-accent h-full transition-[width] duration-300" style={{ width: `${progress}%` }} /></div></div></div>
    <div key={q.id} className="animate-[sf-enter_320ms_cubic-bezier(0.22,1,0.36,1)_both]">{effectiveType === "flashcard" ? <FlashcardPanel q={q} flipped={session.flipped} onFlip={flip} onGrade={grade} /> : effectiveType === "tf" ? <TrueFalsePanel q={q} selected={session.selected} revealed={session.revealed} onSelect={select} /> : effectiveType === "type" ? <TypePanel q={q} value={typed} onChange={setTyped} revealed={session.revealed} correct={last?.correct} onSubmit={submit} /> : <McqPanel q={q} selected={session.selected} revealed={session.revealed} onSelect={select} />}</div>
    {q.hints.length > 0 && effectiveType !== "flashcard" && !session.revealed && <div className="flex flex-col items-start gap-2"><button type="button" onClick={hint} disabled={session.hintLevel >= q.hints.length} className="inline-flex items-center gap-2 text-sm font-medium text-accent min-h-11 disabled:opacity-40"><Lightbulb className="size-4" />{session.hintLevel >= q.hints.length ? "No more hints" : `Show hint ${session.hintLevel + 1}`}</button>{session.hintLevel > 0 && <ul className="text-sm text-muted space-y-1 pl-1">{q.hints.slice(0, session.hintLevel).map((h) => <li key={h}>{h}</li>)}</ul>}</div>}
    {session.revealed && effectiveType !== "flashcard" && <Feedback correct={Boolean(last?.correct)} explanation={q.explanation} example={q.example} answer={correctLabel(q)} />}
    {session.revealed && effectiveType !== "flashcard" && <div className="flex justify-end"><Button onClick={next}>{isLast ? "Finish Session" : "Next Question"} <ArrowLeft className="size-4 rotate-180" /></Button></div>}
  </div>;
}

function formatClock(seconds: number) { return `${Math.floor(seconds / 60)}:${String(seconds % 60).padStart(2, "0")}`; }

function McqPanel({ q, selected, revealed, onSelect }: { q: Question; selected: string | null; revealed: boolean; onSelect: (v: string) => void }) {
  const correct = correctLabel(q); const letters = ["A", "B", "C", "D"];
  return <div className="sf-card p-5 sm:p-10 space-y-8"><div><span className="text-xs font-semibold uppercase tracking-wider text-subtle">Multiple Choice</span><h2 className="mt-3 text-xl sm:text-2xl text-fg leading-snug">{q.prompt}</h2></div><div className="grid grid-cols-1 sm:grid-cols-2 gap-3">{q.choices.map((choice, i) => { const isCorrect = choice === correct; const state = revealed && isCorrect ? "correct" : revealed && selected === choice ? "wrong" : selected === choice ? "picked" : "idle"; return <button key={`${choice}-${i}`} type="button" disabled={revealed} onClick={() => onSelect(choice)} className={cn("min-h-20 sm:min-h-24 rounded-xl text-left p-4 text-sm sm:text-base font-medium border transition-[background-color,border-color,transform,box-shadow] duration-200", state === "idle" && "border-border bg-surface hover:border-accent hover:bg-accent-soft/40", state === "picked" && "border-accent bg-accent-soft", state === "correct" && "border-success bg-success-soft", state === "wrong" && "border-danger bg-danger-soft") }><span className="text-subtle mr-2 tabular-nums">{letters[i]}.</span>{choice}</button>; })}</div></div>;
}

function TrueFalsePanel({ q, selected, revealed, onSelect }: { q: Question; selected: string | null; revealed: boolean; onSelect: (v: string) => void }) { const options = q.choices.length ? q.choices : ["True", "False"]; const correct = correctLabel(q); return <div className="sf-card p-6 sm:p-10 space-y-8"><h2 className="text-xl sm:text-2xl text-fg leading-snug text-center">{q.prompt}</h2><div className="grid grid-cols-1 sm:grid-cols-2 gap-4">{options.map((opt) => { const state = revealed && opt === correct ? "correct" : revealed && selected === opt ? "wrong" : "idle"; return <button key={opt} type="button" disabled={revealed} onClick={() => onSelect(opt)} className={cn("min-h-24 rounded-xl font-semibold text-lg border transition-colors", state === "idle" && "border-border bg-surface hover:border-accent hover:bg-accent-soft/40", state === "correct" && "border-success bg-success-soft", state === "wrong" && "border-danger bg-danger-soft")}>{opt}</button>; })}</div></div>; }

function TypePanel({ q, value, onChange, revealed, correct, onSubmit }: { q: Question; value: string; onChange: (v: string) => void; revealed: boolean; correct?: boolean; onSubmit: () => void }) { return <div className="sf-card p-6 sm:p-12 space-y-8"><h2 className="text-xl sm:text-2xl text-fg leading-snug text-center">{q.prompt}</h2><div className="max-w-md mx-auto w-full space-y-4"><input type="text" value={value} onChange={(e) => onChange(e.target.value)} disabled={revealed} autoFocus placeholder="Type your answer" className={cn("sf-input text-center text-lg", revealed && correct && "border-success", revealed && correct === false && "border-danger")} aria-label="Your answer" />{!revealed && <Button className="w-full" onClick={onSubmit} disabled={!value.trim()}>Submit Answer</Button>}</div></div>; }

function FlashcardPanel({ q, flipped, onFlip, onGrade }: { q: Question; flipped: boolean; onFlip: () => void; onGrade: (knew: boolean) => void }) { return <div className="space-y-5"><div className="flip-scene min-h-[280px] sm:min-h-[340px]"><button type="button" onClick={onFlip} className={cn("flip-card w-full min-h-[280px] sm:min-h-[340px] relative", flipped && "is-flipped")} aria-label={flipped ? "Show prompt" : "Show answer"}><div className="flip-face sf-card absolute inset-0 flex flex-col items-center justify-center p-8 text-center"><span className="text-[10px] uppercase tracking-[0.18em] font-semibold text-subtle mb-4">Prompt</span><p className="text-xl sm:text-2xl text-fg leading-snug">{q.prompt}</p><span className="mt-8 text-xs text-subtle">Tap to reveal</span></div><div className="flip-face flip-back sf-card absolute inset-0 flex flex-col items-center justify-center p-8 text-center bg-accent-soft"><span className="text-[10px] uppercase tracking-[0.18em] font-semibold text-accent mb-4">Answer</span><p className="text-xl sm:text-2xl text-fg leading-snug">{correctLabel(q)}</p>{q.explanation && <p className="mt-4 text-sm text-muted max-w-md">{q.explanation}</p>}</div></button></div>{flipped && <div className="grid grid-cols-2 gap-3"><Button variant="secondary" onClick={() => onGrade(false)}><X className="size-4" /> Review again</Button><Button onClick={() => onGrade(true)}><Check className="size-4" /> I knew it</Button></div>}</div>; }

function Feedback({ correct, explanation, example, answer }: { correct: boolean; explanation: string; example?: string; answer: string }) { return <div className={cn("rounded-xl p-4 sm:p-5 animate-[sf-enter_250ms_cubic-bezier(0.22,1,0.36,1)_both] space-y-3", correct ? "bg-success-soft" : "bg-danger-soft")}><p className="font-semibold font-sans flex items-center gap-2">{correct ? <><Check className="size-4 text-success" /> Correct</> : <><X className="size-4 text-danger" /> Not quite</>}</p>{!correct && <p className="text-sm text-fg">Answer: <span className="font-medium">{answer}</span></p>}{explanation && <p className="text-sm text-muted leading-relaxed">{explanation}</p>}{example && <div className="rounded-lg bg-surface/60 p-3"><p className="text-[10px] uppercase tracking-wider font-bold text-subtle mb-1">Example</p><p className="text-sm text-fg leading-relaxed">{example}</p></div>}</div>; }

export function ResultsView() { const session = useAppStore((s) => s.session); const navigate = useAppStore((s) => s.navigate); const start = useAppStore((s) => s.startSession); const sets = useAppStore((s) => s.studySets); const stats = useMemo(() => { if (!session) return { score: 0, correct: 0, total: 0, time: "0m 00s" }; const total = session.answers.length || session.questions.length; const correct = session.answers.filter((a) => a.correct).length; return { score: total ? Math.round(correct / total * 100) : 0, correct, total, time: formatElapsed((session.finishedAt ?? Date.now()) - session.startedAt) }; }, [session]); const set = sets.find((x) => x.id === session?.setId); const analytics = set ? getSetAnalytics(set) : null; return <div className="max-w-[760px] mx-auto text-center space-y-8 py-4 sm:py-8 stagger-in"><ScoreRing value={stats.score} /><div className="space-y-2"><h1 className="text-3xl text-fg">Session Complete</h1><p className="text-muted">{set ? `You reviewed ${set.subject.toLowerCase()} with adaptive learning data.` : "Nice session."}</p></div><div className="grid grid-cols-2 sm:grid-cols-4 gap-3"><StatCard label="Score" value={`${stats.score}%`} /><StatCard label="Correct" value={`${stats.correct}/${stats.total}`} accent /><StatCard label="Time" value={stats.time} /><StatCard label="Mastered" value={String(analytics?.mastered ?? 0)} /></div><div className="sf-card p-5 text-left grid grid-cols-2 sm:grid-cols-4 gap-4"><Mini label="Accuracy" value={`${analytics?.accuracy ?? 0}%`} /><Mini label="Reviews" value={String(analytics?.reviews ?? 0)} /><Mini label="Due" value={String(analytics?.due ?? 0)} /><Mini label="Attempts" value={String(analytics?.attempts ?? 0)} /></div><div className="flex flex-col sm:flex-row justify-center gap-3"><Button variant="secondary" onClick={() => navigate("library")}><ArrowLeft className="size-4" /> Return to Library</Button><Button onClick={start}><RotateCcw className="size-4" /> Study Again</Button></div></div>; }
function Mini({ label, value }: { label: string; value: string }) { return <div><span className="block text-[10px] uppercase tracking-wider text-subtle">{label}</span><span className="text-lg font-semibold text-fg tabular-nums">{value}</span></div>; }
function StatCard({ label, value, accent }: { label: string; value: string; accent?: boolean }) { return <div className="sf-card p-4 sm:p-5 text-center"><span className="block text-xs text-subtle mb-1">{label}</span><span className={cn("text-xl sm:text-2xl font-bold font-sans tabular-nums", accent ? "text-success" : "text-fg")}>{value}</span></div>; }
function ScoreRing({ value }: { value: number }) { const [shown, setShown] = useState(0); useEffect(() => { const reduce = window.matchMedia("(prefers-reduced-motion: reduce)").matches; if (reduce) { setShown(value); return; } let frame = 0; const start = performance.now(); const tick = (now: number) => { const t = Math.min(1, (now - start) / 700); setShown(Math.round(value * (1 - Math.pow(1 - t, 3)))); if (t < 1) frame = requestAnimationFrame(tick); }; frame = requestAnimationFrame(tick); return () => cancelAnimationFrame(frame); }, [value]); const r = 42, c = 2 * Math.PI * r, offset = c - shown / 100 * c; return <div className="relative mx-auto size-28"><svg viewBox="0 0 100 100" className="-rotate-90 size-28" aria-hidden="true"><circle cx="50" cy="50" r={r} fill="none" stroke="var(--sf-surface-2)" strokeWidth="8" /><circle cx="50" cy="50" r={r} fill="none" stroke="var(--sf-accent)" strokeWidth="8" strokeLinecap="round" strokeDasharray={c} strokeDashoffset={offset} /></svg><div className="absolute inset-0 flex items-center justify-center"><span className="font-sans font-semibold text-2xl tabular-nums text-fg">{shown}%</span></div></div>; }
